# Generated by Django 5.1.2 on 2024-10-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('diameter', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
